-- 코드를 입력하세요
SELECT A.USER_ID,
       A.PRODUCT_ID
FROM ONLINE_SALE A, ONLINE_SALE B
WHERE A.ONLINE_SALE_ID = B.ONLINE_SALE_ID
    AND A.USER_ID = B.USER_ID
GROUP BY A.USER_ID,
         A.PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY A.USER_ID, A.PRODUCT_ID DESC;