-- 코드를 작성해주세요
WITH RECURSIVE GEN AS ( -- GEN 테이블에 ID와 GENERATION 필드가 있음
    -- PARENT
    SELECT ID, 1 AS GENERATION
    FROM   ECOLI_DATA
    WHERE  PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, G.GENERATION + 1
    FROM   ECOLI_DATA E, GEN G
    WHERE  E.PARENT_ID = G.ID

) -- CTE는 해당 SQL문 전체에서 살아있다.
SELECT COUNT(*),
       G.GENERATION
FROM   GEN G
    LEFT JOIN ECOLI_DATA E ON (G.ID = E.PARENT_ID)
WHERE  E.PARENT_ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;