-- 코드를 입력하세요
WITH AVAILABILITIES AS (

    SELECT CAR_ID,
           '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-16'
        AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-10-16'
    
)
SELECT C.CAR_ID,
       NVL(A.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    LEFT JOIN AVAILABILITIES A ON C.CAR_ID = A.CAR_ID
GROUP BY C.CAR_ID, A.AVAILABILITY
ORDER BY C.CAR_ID DESC;