-- 코드를 입력하세요
WITH HOURS AS (

    SELECT LEVEL - 1 AS HOUR -- LEVEL은 1부터 시작하기 때문
    FROM DUAL -- DUMMY
    CONNECT BY LEVEL <= 24 -- -1 했으니 24까지.. 24 - 1 = 23
    
), ANIMAL_OUTS_COUNT AS (

    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
         , COUNT(*) AS COUNT
    FROM   ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
    ORDER BY HOUR

)
SELECT H.HOUR
     , NVL(A.COUNT, 0) AS COUNT
FROM   HOURS H
    LEFT JOIN ANIMAL_OUTS_COUNT A
        ON H.HOUR = A.HOUR
ORDER BY H.HOUR;

