-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
     , COUNT(*) AS COUNT
FROM   ANIMAL_OUTS
WHERE  TO_CHAR(DATETIME, 'HH24:MI') >= '09:00'
    AND TO_CHAR(DATETIME, 'HH24:MI') <= '19:59'
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
ORDER BY HOUR;