-- 코드를 작성해주세요
# SELECT I1.ITEM_ID,
#        I1.ITEM_NAME,
#        I1.RARITY
# FROM ITEM_INFO I1, ITEM_TREE T
# WHERE I1.ITEM_ID = T.ITEM_ID
#     AND T.PARENT_ITEM_ID
#         IN (
#             SELECT ITEM_ID
#             FROM   ITEM_INFO
#             WHERE  RARITY = 'RARE'
#         )
# ORDER BY I1.ITEM_ID DESC;

SELECT I1.ITEM_ID,
       I1.ITEM_NAME,
       I1.RARITY
FROM ITEM_INFO I1, ITEM_INFO I2, ITEM_TREE T
WHERE I1.ITEM_ID = T.ITEM_ID
    AND T.PARENT_ITEM_ID = I2.ITEM_ID
    AND I2.RARITY = 'RARE'
ORDER BY I1.ITEM_ID DESC;
