-- 코드를 입력하세요
WITH RENT_COUNT AS (

    SELECT H.*
         , COUNT(*) OVER(PARTITION BY CAR_ID) AS TOTAL_COUNT
    FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE  TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08'
        AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'

)
SELECT TO_NUMBER(TO_CHAR(R.START_DATE, 'MM')) AS MONTH
     , R.CAR_ID
     , COUNT(*) AS RECORDS
FROM   RENT_COUNT R
WHERE  TOTAL_COUNT >= 5
GROUP BY TO_CHAR(R.START_DATE, 'MM'), R.CAR_ID
ORDER BY MONTH, R.CAR_ID DESC;

