-- 코드를 작성해주세요
SELECT DISTINCT(ID) AS ID,
       EMAIL,
       FIRST_NAME,
       LAST_NAME
  FROM DEVELOPERS D, SKILLCODES C
 WHERE D.SKILL_CODE & C.CODE
    AND (C.NAME = 'C#' OR C.NAME = 'Python')
 ORDER BY ID;