-- 코드를 작성해주세요
WITH MAX_SIZE AS (
    
    SELECT ID,
           MAX(SIZE_OF_COLONY) AS SIZE,
           YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM   ECOLI_DATA
    GROUP BY YEAR
    
)
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
       M.SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
       E.ID
FROM   ECOLI_DATA E
    LEFT JOIN MAX_SIZE M ON YEAR(DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV;