-- 코드를 작성해주세요
WITH MAX_LENGTHS AS (
    
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM   FISH_INFO
    GROUP BY FISH_TYPE
    
)
SELECT I.ID,
       N.FISH_NAME,
       I.LENGTH
FROM   FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    JOIN MAX_LENGTHS M ON I.FISH_TYPE = M.FISH_TYPE
WHERE I.LENGTH = M.MAX_LENGTH
ORDER BY I.ID;